DROP DATABASE IF EXISTS hcmut_spss;

CREATE DATABASE hcmut_spss
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_unicode_ci;
USE hcmut_spss;


CREATE TABLE SPSO (
  SPSO_ID INT AUTO_INCREMENT, 
  USERNAME VARCHAR(32) NOT NULL UNIQUE,
  PASSWORD VARCHAR(128) NOT NULL,
  PRIMARY KEY(SPSO_ID)
) ENGINE=InnoDB;

CREATE TABLE PRINTER (
  PRINTER_ID INT AUTO_INCREMENT, 
  BUILDING VARCHAR(32) NOT NULL,
  ROOM VARCHAR(32) NOT NULL,
  MODEL VARCHAR(32),
  IS_ACTIVE BOOLEAN NOT NULL,
  PAPER INT,
  PRIMARY KEY (PRINTER_ID)
) ENGINE=InnoDB;

